name: dev

on:
  push:
    branches: [ main ]

jobs:
  build-mariadb:
    if: "!contains(github.event.head_commit.message, '#release')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PA_TOKEN }}
        submodules: true
    - name: Docker login
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
    - name: Build container
      run: docker build -f docker/mariadb/Dockerfile -t ghcr.io/gurbaninow/database:dev .
    - name: Publish container
      run: docker push ghcr.io/gurbaninow/database:dev

  build-sqlite:
    if: "!contains(github.event.head_commit.message, '#release')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PA_TOKEN }}
        submodules: true
    - uses: actions/setup-node@v3
    - run: npm ci
    - name: Build database
      run: npm run build-sqlite
    - name: Store database artifact
      uses: actions/upload-artifact@v3
      with:
        name: database.sqlite
        path: build/database.sqlite
